export const TEST_INVOICE = {
  id: 'TEST',
  currency: '$',
  currentDate: '2023-01-01',
  invoiceNumber: 1,
  dateOfIssue: '2023-01-01',
  billTo: 'Test2',
  billToEmail: 'Test2@test.com',
  billToAddress: 'Test2 Address',
  billFrom: 'Test1',
  billFromEmail: 'Test1@test.com',
  billFromAddress: 'Test1 Address',
  notes: 'Thanks for your business!',
  total: '10.80',
  subTotal: '10.00',
  taxRate: '18',
  taxAmmount: '1.80',
  discountRate: '10',
  discountAmmount: '1.00',
  items: [
    {
      id: '0',
      name: 'Test Item',
      description: 'Test',
      price: '10.00',
      quantity: '1',
    },
  ],
};
